version: 2.1

jobs:
  build-openwrt:
    docker:
      - image: openwrtorg/sdk:x86-64  # docker 执行器
    environment:
      TZ: Asia/Shanghai
    steps:
      - checkout
      - run: pwd && ls -la && ls -la ..

workflows:
  version: 2
  build-workflow:
    jobs:
      - build-openwrt:
          filters:
            branches:
              only: main
